import Foundation

nonisolated enum HermesPluginContent {
  static let pluginName = "supacode-presence"
  static let ownershipMarker = AgentHookSettingsCommand.ownershipMarker

  static let manifestFileName = "plugin.yaml"
  static let moduleFileName = "__init__.py"

  static func manifest() -> String {
    """
    name: \(pluginName)
    version: "1.0.0"
    description: Report Hermes agent presence and turn notifications to Supacode via OSC 3008.
    author: Supacode
    hooks:
      - on_session_start
      - pre_llm_call
      - transform_llm_output
      - on_session_end
    provides_hooks:
      - on_session_start
      - pre_llm_call
      - transform_llm_output
      - on_session_end
    """
  }

  static func module() -> String {
    """
    \"\"\"Supacode presence bridge for Hermes.\"\"\"

    # \(ownershipMarker)
    # Generated by Supacode. Do not edit. The plugin writes OSC 3008 directly
    # to Hermes' controlling TTY and is inert outside Supacode surfaces.

    import base64
    import json
    import os

    AGENT = "hermes"
    # Byte caps match the app so the base64 sequence stays under libghostty's 2048-byte OSC ceiling.
    NOTIFY_TITLE_BUDGET = 160
    NOTIFY_BODY_BUDGET = 1000


    def register(ctx):
        ctx.register_hook("on_session_start", _on_session_start)
        ctx.register_hook("pre_llm_call", _pre_llm_call)
        ctx.register_hook("transform_llm_output", _transform_llm_output)
        ctx.register_hook("on_session_end", _on_session_end)


    def _is_supacode_surface():
        return bool(os.environ.get("SUPACODE_SURFACE_ID"))


    def _local_pid_suffix():
        return f";pid={os.getpid()}" if os.environ.get("SUPACODE_SOCKET_PATH") else ""


    def _write_to_terminal(sequence):
        try:
            fd = os.open("/dev/tty", os.O_WRONLY)
        except OSError:
            return
        try:
            data = sequence.encode("utf-8")
            offset = 0
            while offset < len(data):
                try:
                    written = os.write(fd, data[offset:])
                    if written <= 0:
                        break
                    offset += written
                except (InterruptedError, BlockingIOError):
                    continue
                except OSError:
                    break
        finally:
            os.close(fd)


    def _emit_presence(state):
        if not _is_supacode_surface():
            return
        action = "end" if state == "session_end" else "start"
        meta = f"event={state}{_local_pid_suffix()}"
        _write_to_terminal(f"\\x1b]3008;{action}={AGENT};{meta}\\x1b\\\\")


    def _notify_field(value, budget):
        escaped = json.dumps(value)[1:-1]
        buf = escaped.encode("utf-8")[:budget]
        return base64.b64encode(buf).decode("ascii")


    def _emit_notification(title, body):
        if not _is_supacode_surface():
            return
        meta = (
            "kind=notify"
            f";title={_notify_field(title, NOTIFY_TITLE_BUDGET)}"
            f";body={_notify_field(body, NOTIFY_BODY_BUDGET)}"
        )
        _write_to_terminal(f"\\x1b]3008;start={AGENT};{meta}\\x1b\\\\")


    def _on_session_start(**_kwargs):
        _emit_presence("session_start")


    def _pre_llm_call(**_kwargs):
        _emit_presence("busy")


    def _transform_llm_output(response_text=None, **_kwargs):
        _emit_presence("idle")
        # Coerce defensively: an in-process plugin must never raise into the agent turn.
        body = response_text.strip() if isinstance(response_text, str) else ""
        if body:
            _emit_notification("Hermes", body)
        return None


    def _on_session_end(**_kwargs):
        # on_session_end fires per turn in Hermes, so emit idle (not session_end) to stay present between turns.
        _emit_presence("idle")
    """
  }
}
